### ISSUE TITLE
RemoteTransform does not apply proper rotation

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [GodotVR/godot_openvr#79]
When using a ``RemoteTransform`` on a ``ARVRController`` the transform of the node is not applied correctly. Could it be that the rotation gets incremented double time?

**Comment by BastiaanOlij** [comment]
Keep in mind that the ARVRController is completely controlled by the ARVRServer pushing tracking information from the VR system to the controller.

If you're also trying to update it with a RemoteTransform you suddenly have two sources of data trying to update the same thing.

I don't know why you're trying to do this but on face value without more info I don't think this will ever have the desired result.

**Comment by MathiasBaumgartinger** [comment]
I am very sorry for my unclear formulation.

The problem i am facing is that when i attach a new node to the VR-Controller that should have the transform of another node but serves the behaviour of the this node it will not apply the transform of the ``RemoteTransform`` properly.

More specifically i implemented a VR-teleport with the "tall-ray"-method, where a ray needs the transform of the ``ARVROrigin``.

Think of a structure like this. To me it felt like mentioned before, the rotation gets incremented double time.
![grafik](https://user-images.githubusercontent.com/33001106/76074554-d2d58680-5f9b-11ea-819b-1e887841cd62.png)

**Comment by vilhalmer** [comment]
I don't think this is/was an issue with this library, it looks like you were using RemoteTransform backwards in that screenshot if I understand what you were trying to achieve. The RemoteTransform should go underneath the source of the rotation, and have its target set to the ray. You'd probably still have the issue with two things trying to update the rotation as well.

Either way, going to close this out for age.
